### PR TITLE
GeoSurprise

### PR DESCRIPTION
**Pull request by gilherau**
First Fabric RTA Demo to be published.

### CODE REVIEW

**Comment by gilherau** [comment]
Initial PR for GeoSurprise

**Comment by gilherau** [comment]
All set

**Review by gilherau — COMMENTED** [review]
I hereby approve!

**Review by gilherau — COMMENTED** [review]
This is grea

**Review by shahdevangp — APPROVED** [review]
Approved

**Review by shahdevangp — APPROVED** [review]
Approved

**Pull request merged**
